#!/usr/bin/env bash
# script that displays information about subdomains.

dns_configuration () {
	ANSWER=$(dig "$2" | grep -A1 'ANSWER SECTION:' | awk 'NR==2 {print $0}')
	echo "The subdomain $1 has a $(echo "$ANSWER" | awk '{print $4}') record and points to $(echo "$ANSWER" | awk '{print $5}')"
}
if [[ $# == 1 ]]; then
	subdomain=('www' 'lb-01' 'web-01' 'web-02')
	for i in "${subdomain[@]}"; do
		CONCAT="$i.$1"
		dns_configuration "$i" "$CONCAT"
	done
else
	CONCAT="$2.$1"
	dns_configuration "$2" "$CONCAT"
fi
