#!/usr/bin/env bash
# Installing nginx
# Configure nginx
# Write into a file
# Creates server block files


sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /etc/nginx/html/index.html

service nginx restart
