#!/usr/bin/env bash
# Configure a new Nginx server
# to have a custom 404 page that contains the string Ceci n'est pas une page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index.html
sudo sh -c "echo \"Ceci n'est pas une page\" > /var/www/html/404.html"
SERVER_CONFIG="server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	# Add index.php to the list if you are using PHP
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
		try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me){
			rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
	}
	error_page 404 /404.html;
	location = /404.html{
		internal;
	}
}"
sudo sh -c "echo '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"
sudo service nginx restart
