#!/usr/bin/env bash
# Configure a new Nginx server
# to have a custom 404 page that contains the string Ceci n'est pas une page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index.html
sudo sh -c "echo \"Ceci n'est pas une page\" > /var/www/html/404.html"

sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default
sudo sed -i '/server_name _;/a error_page 404 /404.html;\nlocation = /404.html {\n    internal;\n    add_header Content-Type text/plain;\n    return 404 '\''Ceci n'\'\''est pas une page'\'';\n}' /etc/nginx/sites-available/default
sudo service nginx restart

