#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header

sudo apt-get -y update
sudo apt-get -y install nginx

sudo sh -c "echo 'Hello World!' > /var/www/html/index.html"
sudo touch /var/www/html/404.html
sudo sh -c "echo \"Ceci n'est pas une page\" > /var/www/html/404.html"
SERVER_CONFIG="server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;

	index index.html index.htm index.nginx-debian.html;

	server_name _;
	add_header X-Served-By $HOSTNAME;

	location / {
		try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me){
			rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
	}
	error_page 404 /404.html;
	location = /404.html{
		internal;
	}
}"
sudo sh -c "echo '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"
sudo service nginx restart
