#!/usr/bin/env bash
# Script that Installs and configures HAproxy

sudo apt-get update
sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee /etc/default/haproxy > /dev/null

LISTEN="
listen lb_server
	bind *:80
	mode http
	balance roundrobin
	option httpclose
	option forwardfor
	server 163139-web-01 34.232.66.28:80 check
	server 163139-web-02 34.207.227.31:80 check
"

echo "$LISTEN" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
sudo service haproxy start
