#!/usr/bin/env bash
# Script that creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely and Displays I hate the kill command when receiving a SIGTERM signal
# Also displays Y U no love me?! when receiving a SIGINT signal and d
# deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

terminator() {
	rm -rf /var/run/myscript.pid
	exit
}

echo $$ > /var/run/myscript.pid

trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"; terminator' SIGTERM
trap terminator SIGQUIT

count=0

while [ $count -ge 0 ]
do
	echo "To infinity and beyond"
	sleep 2
done

