#!/usr/bin/env bash
# Script that displays the content of the file /etc/passwd
# Displaying username, user id, home directory path for the user


while IFS=: read -r username _ userid _ _ homedir _
do
	echo "Username: $username"
	echo "User ID: $userid"
	echo "Home Directory: $homedir"
	echo ""
done < /etc/passwd
