#!/usr/bin/env bash
# A BASH Script that runs nignx webserver as nginx and also configures nginx to
# listen to port 8080

sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
